name = "ai-elements-vue"
main = ".output/server/index.mjs"
compatibility_date = "2024-07-06"

[vars]
# Add environment variables here if needed, e.g. API keys

routes = [ "registry.ai-elements-vue.com/*" ]
