name: Setup
description: Installs Node, enables Corepack, and caches pnpm.

runs:
  using: composite

  steps:
    - name: Use Latest Corepack
      shell: bash
      run: |
        echo "Before: corepack version => $(corepack --version || echo 'not installed')"
        npm i -g corepack@latest
        echo "After : corepack version => $(corepack --version)"
        corepack enable
        pnpm --version || true

    - name: Setup node & pnpm
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm
        registry-url: https://registry.npmjs.org
